# Generated by Django 3.2 on 2022-08-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owners_name', models.CharField(max_length=100)),
                ('owners_phone_1', models.CharField(help_text='+255 format', max_length=15)),
                ('house_owner', models.CharField(max_length=100)),
                ('number_of_rooms', models.PositiveIntegerField(default=0)),
                ('price_per_day', models.PositiveIntegerField(default=0)),
                ('minimum_booking_per_day', models.PositiveIntegerField(default=0)),
                ('instructions', models.TextField()),
                ('description', models.TextField()),
                ('region', models.CharField(choices=[('Arusha', 'Arusha'), ('Dar es Salaam ', 'Dar es Salaam'), ('Dodoma', 'Dodoma'), ('Geita', 'Geita'), ('Iringa', 'Iringa'), ('Kagera', 'Kagera'), ('Katavi', 'Katavi'), ('Kigoma', 'Kigoma'), ('Kilimanjaro', 'Kilimanjaro'), ('Lindi', 'Lindi'), ('Manyara', 'Manyara'), ('Mara', 'Mara'), ('Mbeya', 'Mbeya'), ('Zanzibar', 'Zanzibar'), ('Morogoro', 'Morogoro'), ('Mtwara', 'Mtwara'), ('Mwanza', 'Mwanza'), ('Njombe', 'Njombe'), ('Pemba North', 'Pemba North'), ('Pemba South', 'Pemba South'), ('Pwani', 'Pwani'), ('Rukwa', 'Rukwa'), ('Ruvuma', 'Ruvuma'), ('Shinyanga', 'Shinyanga'), ('Simiyu', 'Simiyu'), ('Singida', 'Singida'), ('Songwe', 'Songwe'), ('Tabora', 'Tabora'), ('Tanga', 'Tanga')], max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=100)),
                ('house_number', models.PositiveIntegerField(default=0)),
                ('google_map', models.CharField(max_length=100)),
                ('ametuer', models.CharField(max_length=100)),
            ],
        ),
    ]
