# Generated by Django 3.2 on 2022-08-04 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_house_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='owners_phone_2',
            field=models.CharField(default=django.utils.timezone.now, help_text='+255 format', max_length=15),
            preserve_default=False,
        ),
    ]
