# Generated by Django 4.1 on 2022-08-10 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_house_owners_phone_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='ametuer',
        ),
        migrations.AddField(
            model_name='house',
            name='amenities',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
