# Generated by Django 3.2 on 2022-08-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(help_text='+255 format', max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
